package com.luciofm.curso.data.provider;

import com.luciofm.curso.data.provider.util.ColumnMetadata;

import android.content.ContentValues;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;
import android.net.Uri;
import android.provider.BaseColumns;
import android.util.Log;

/**
 * This class was generated by the ContentProviderCodeGenerator project made by Foxykeep
 * <p>
 * (More information available https://github.com/foxykeep/ContentProviderCodeGenerator)
 */
public abstract class CursoContent {

    public static final Uri CONTENT_URI = Uri.parse("content://" + CursoProvider.AUTHORITY);

    private CursoContent() {
    }

    /**
     * Created in version 1
     */
    public static final class CursoPessoas extends CursoContent {

        private static final String LOG_TAG = CursoPessoas.class.getSimpleName();

        public static final String TABLE_NAME = "cursoPackages";
        public static final String TYPE_ELEM_TYPE = "vnd.android.cursor.item/curso-cursopackages";
        public static final String TYPE_DIR_TYPE = "vnd.android.cursor.dir/curso-cursopackages";

        public static final Uri CONTENT_URI = Uri.parse(CursoContent.CONTENT_URI + "/" + TABLE_NAME);

        public static enum Columns implements ColumnMetadata {
            ID(BaseColumns._ID, "integer"),
            NOME("nome", "text"),
            EMAIL("email", "text");

            private final String mName;
            private final String mType;

            private Columns(String name, String type) {
                mName = name;
                mType = type;
            }

            @Override
            public int getIndex() {
                return ordinal();
            }

            @Override
            public String getName() {
                return mName;
            }

            @Override
            public String getType() {
                return mType;
            }
        }

        public static final String[] PROJECTION = new String[] {
                Columns.ID.getName(),
                Columns.NOME.getName(),
                Columns.EMAIL.getName()
        };

        private CursoPessoas() {
            // No private constructor
        }

        public static void createTable(SQLiteDatabase db) {
            db.execSQL("CREATE TABLE " + TABLE_NAME + " (" + Columns.ID.getName() + " " + Columns.ID.getType() + ", " + Columns.NOME.getName() + " " + Columns.NOME.getType() + ", " + Columns.EMAIL.getName() + " " + Columns.EMAIL.getType() + ", PRIMARY KEY (" + Columns.ID.getName() + ")" + ");");

            db.execSQL("CREATE INDEX cursoPackages_email on " + TABLE_NAME + "(" + Columns.EMAIL.getName() + ");");
        }

        // Version 1 : Creation of the table
        public static void upgradeTable(SQLiteDatabase db, int oldVersion, int newVersion) {

            if (oldVersion < 1) {
                Log.i(LOG_TAG, "Upgrading from version " + oldVersion + " to " + newVersion
                        + ", data will be lost!");

                db.execSQL("DROP TABLE IF EXISTS " + TABLE_NAME + ";");
                createTable(db);
                return;
            }


            if (oldVersion != newVersion) {
                throw new IllegalStateException("Error upgrading the database to version "
                        + newVersion);
            }
        }

        static String getBulkInsertString() {
            return new StringBuilder("INSERT INTO ").append(TABLE_NAME).append(" ( ").append(Columns.ID.getName()).append(", ").append(Columns.NOME.getName()).append(", ").append(Columns.EMAIL.getName()).append(" ) VALUES (?, ?, ?)").toString();
        }

        static void bindValuesInBulkInsert(SQLiteStatement stmt, ContentValues values) {
            int i = 1;
            String value;
            stmt.bindLong(i++, values.getAsLong(Columns.ID.getName()));
            value = values.getAsString(Columns.NOME.getName());
            stmt.bindString(i++, value != null ? value : "");
            value = values.getAsString(Columns.EMAIL.getName());
            stmt.bindString(i++, value != null ? value : "");
        }
    }
}

